// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKT-wZj7lJUe9a15Z9RmP98ULjslbRaRc',
    appId: '1:647736437102:web:beeafe26f148b6ee66f97f',
    messagingSenderId: '647736437102',
    projectId: 'inkquest-ts',
    authDomain: 'inkquest-ts.firebaseapp.com',
    storageBucket: 'inkquest-ts.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClPc-QfHgOzPyTV3rg4siu-wjROQsb_2A',
    appId: '1:647736437102:android:e511c04e8b6f5a2b66f97f',
    messagingSenderId: '647736437102',
    projectId: 'inkquest-ts',
    storageBucket: 'inkquest-ts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoJYe7ABYUOFucETCpFUQTnTdCsMo0JHw',
    appId: '1:647736437102:ios:a889956d3667680366f97f',
    messagingSenderId: '647736437102',
    projectId: 'inkquest-ts',
    storageBucket: 'inkquest-ts.appspot.com',
    iosBundleId: 'com.example.inkquestTravissimmons',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoJYe7ABYUOFucETCpFUQTnTdCsMo0JHw',
    appId: '1:647736437102:ios:122aa0d8e1b3509966f97f',
    messagingSenderId: '647736437102',
    projectId: 'inkquest-ts',
    storageBucket: 'inkquest-ts.appspot.com',
    iosBundleId: 'com.example.inkquestTravissimmons.RunnerTests',
  );
}
